CREATE TABLE TEMP1 
 (	ID NUMBER, 
    CONSTRAINT TEMP1_PK PRIMARY KEY(ID)
 ) ;
 
 DROP TABLE TEMP1;
 
 CREATE TABLE TEMP2 
 (	
    ID NUMBER,
    TEMP1_ID NUMBER,
    VAL VARCHAR2(250),
    CONSTRAINT TEMP2_PK PRIMARY KEY(ID),
    CONSTRAINT TEMP1_FK FOREIGN KEY(TEMP1_ID) REFERENCES TEMP1(ID)
 ) ;